"""add add columns for scan limitation

Revision ID: c20bbc52a1b7
Revises: 730a26ac9df0
Create Date: 2025-05-08 14:45:04.969748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20bbc52a1b7'
down_revision: Union[str, None] = '730a26ac9df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_information', sa.Column('scan_limitation', sa.Integer(), nullable=True))
    op.add_column('device_information', sa.Column('scan_reseted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_information', 'scan_reseted_at')
    op.drop_column('device_information', 'scan_limitation')
    # ### end Alembic commands ###
