"""add ad_reward

Revision ID: 730a26ac9df0
Revises: 8116343fad2c
Create Date: 2025-05-08 09:20:12.272678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730a26ac9df0'
down_revision: Union[str, None] = '8116343fad2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_reward',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('guest_id', sa.String(length=255), nullable=True),
    sa.Column('reward_token', sa.String(length=255), nullable=False),
    sa.Column('ad_network', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reward_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_reward')
    # ### end Alembic commands ###
